<?php echo $this->partial('partial/menu.phtml', array('breadcrumb' => 'Home')); ?>
<div class="col-sm-10">
    <?php
    $form = $this->form;
    $formLabel = $this->plugin('formLabel');

    $form->setAttribute('method', 'post');
    $form->setAttribute('action', $this->url('doAdd'));
    $form->prepare();

    echo $this->form()->openTag($form);
    ?>

    <div class="form-group">
        <?php
        $op1 = $form->get('op1');
        echo $formLabel->openTag($op1) . $op1->getOption('label') . $formLabel->closeTag();
        ?>
        <div class="col-sm-10">
            <?php
            echo $this->formInput($op1);
            echo $this->formElementErrors($op1);
            ?>
        </div>
    </div>
    <div class="form-group">
        <?php
        $op2 = $form->get('op2');
        echo $formLabel->openTag($op2) . $op2->getOption('label') . $formLabel->closeTag();
        ?>
        <div class="col-sm-10">
            <?php
            echo $this->formInput($op2);
            echo $this->formElementErrors($op2);
            ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->formElement($form->get('calc')) ?>
        </div>
    </div>
</div>